stages:         
  - test

matlab-test-job:   
  tags: 
    - matlab
  stage: test
  script:
    - matlab -batch "openProject('OrganizingData.prj'); results = runtests('IncludeSubfolders', true); assertSuccess(results);"